### PR TITLE
Revert "OPI Device Provisioning and Lifecycle Spec"

### PR DESCRIPTION
**Pull request by glimchb**
@Gal-Zaidman decision to revert

### CODE REVIEW

**Review by dandaly — APPROVED** [review]
Once this is reverted I will repost as a PR.

**Comment by ballle98** [comment]
Has the PR been reposted?

**Comment by dandaly** [comment]
The original document is still there: https://github.com/opiproject/opi-prov-life/blob/main/OPI_DEVICE_PROV_LIFE.mdDanOn Feb 6, 2024, at 7:19 AM, Lee Ballard ***@***.***> wrote:﻿
Has the PR been reposted?

**Comment by Gal-Zaidman** [comment]
@glimchb can you close the PR since we are doing changes on the merged file instead?

**Pull request closed without merging**
