### PR TITLE
Update COORDINATION.md

### PR DESCRIPTION
**Pull request by RezaBacchus**
Added Use Cases and Assumptions

### CODE REVIEW

**Review by glimchb — APPROVED** [review]
good start, we can iterate on this now

**Comment by glimchb** [comment]
@RezaBacchus markdown still fails on tabs/spaces, please fix so I can merge it

**Comment by RezaBacchus** [comment]
Greetings Boris:
I tried again.

Below is the corrected content I am trying to include.  Please add it if my latest attempt did not work.
Thanks in advance
Reza

##Use cases

This proposal applies to the following use cases:

1.  One or more xPUs in a single server
2.  A single xPU attached to multiple CPUs within the same server
3.  The xPU is powered on at the same time as the server BMC using Auxiliary power
4.  The server BMC controls when the xPU and server CPUs are powered with Primary power
5.  The xPU boots from the network or on-board non-volatile storage
6.  xPUs with and without a local Add-in Management Controller (AMC)

The multi-host case where one or more xPUs are attached to multiple servers within an enclosure is deferred to another exercise.  This requires a Chassis Management Controller (CMC).

##Assumptions

1.  While the xPU is powered by 3.3Vaux only

	1.  OOB communications from the server BMC shall be limited to accessing the FRU (EEPROM) and/or security chip on the xPU if they are available
	2.  There shall be no IB communication from the server CPU because it is in S5 state (powered off)

2.  The xPU may ignore transitions in the PERST# signal
3.  The xPU may require separate mechanisms to reset its PCIe interface and compute complex
4.  The xPU may start to boot as soon as it detects the stable application of +12V and +3.3V
5.  The xPU is agnostic as to if +12V and +3V are derived from Primary or Auxiliary power
6.  The xPU has no dependencies on the status of the server OS
7.  The server OS may have dependencies on a booted xPU, but may continue to boot when the xPU fails to boot after some appropriate timeout
8.  The xPU may or may not be the only network data path (tenant) to the host OS
9.  Downstream Port Containment (DPC) is not a practical mechanism to hot add PCIe functions during POST
10.  When an xPU is equipped with an AMC it shall be subservient to the server BMC.  Other cases will be considered later.

**Comment by glimchb** [comment]
I merged the use case section to https://github.com/opiproject/opi-prov-life/blob/main/BOOTSEQ.md#use-cases

**Comment by glimchb** [comment]
Assumption section from https://github.com/opiproject/opi-prov-life/blob/62881ca42d98e0255ca194cb774cf2d6dc1fef31/COORDINATION.md#assumptions 
should be merged to https://github.com/opiproject/opi-prov-life/blob/main/BOOTSEQ.md#assumptions

**Comment by glimchb** [comment]
merged #205 instead

**Pull request closed without merging**
