### PR TITLE
   [Documentation]: sZTP & FIDO comparison

### PR DESCRIPTION
**Pull request by Ganesh-Juniper**
High level comparison of sZTP(RFC-8572) and FIDO for DPU provisioning.

Signed-off-by: Ganesh-Juniper <gbmsatjuni@gmail.com>

### CODE REVIEW

**Review by glimchb — APPROVED** [review]
lgtm

**Review by mestery — CHANGES_REQUESTED** [review]
Please, lets not check in PDF files, but instead make this a markdown that we can review.

**Comment by Ganesh-Juniper** [comment]
@mestery  let me convert it to markdown and update it. Thanks

**Comment by mestery** [comment]
> @mestery let me convert it to markdown and update it. Thanks

Thanks! It is much easier to review and provide edits to markdown than PDF files. Appreciate you converting this!

**Pull request closed without merging**
