### PR TITLE
Initial architecture proposal

### PR DESCRIPTION
**Pull request by tedstreete**
Initial proposal for telemetry architecture, consisting of one mini-aggregator per DPU, optionally 
feeding into one or ore macro-aggregators. 

OPI will define a minimum set of protocols for feeding the mini-aggregator, and exporting from the 
mini-aggregator. Any service that supports the minimum set of protocols can be used for aggregating 
the feeds, and persisting any data.

The example services for aggregation and persistence are just examples...

Signed-off-by: Ted Streete <ted.streete@dell.com>

### CODE REVIEW

**Review by glimchb — APPROVED** [review]
good start

**Comment by tedstreete** [comment]
@mestery I"m not familiar with "editable PNG". Is that a normal PNG, or something different, and how do I generate one from draw.io?

**Comment by mestery** [comment]
Screen Shot 2022-04-07 at 2 15 06 PM

Hi @tedstreete, see the pic above. When using draw.io to generate these drawings, select `editable bitmap image`. In this way, any program which can display png files can display it as a graphic, but when you open it with draw.io, you can edit the image. Make sense?

**Comment by tedstreete** [comment]
@mestery It does, thank you. I was trying to 'export' it to editable PNG, not 'save as...'.

I'll update the PR.

**Review by mestery — APPROVED** [review]
image

**Review by glimchb — APPROVED** [review]
lgtm

**Pull request merged**
