### PR TITLE
add ARM assumption

### PR DESCRIPTION
**Pull request by glimchb**
from today meeting comments

### CODE REVIEW

**Comment by dandaly** [comment]
This isn't really an assumption on the proposal, it is just a detail around how you support OROM.  Can we move this into the Terms definitions for OROM instead?  Currently it says:

Option ROM used by a device to provide a driver to BIOS for booting

Why not just change this to:

Option ROM used by a device to provide a driver to BIOS for booting, one ROM image per supported host CPU architecture (x86, ARM, etc.).

**Comment by glimchb** [comment]
> This isn't really an assumption on the proposal, it is just a detail around how you support OROM. 
it is kinda assumption or even requirement for this solution to support ARM, because we see a lot of NICs and DPUs they don't support arm using OROM...

**Comment by samerhaj** [comment]
Just for awareness: PCIe devices, including DPUs, that are to be supported in Arm-based servers, are *required* to carry AARCH64 UEFI OptionROMs, per the Arm [SBBR ](https://developer.arm.com/documentation/den0044/latest)requirements (section 7.3.3.1 - UEFI drivers).

These requirements are enforced as part of the [Arm SystemReady certification program](https://www.arm.com/architecture/system-architectures/systemready-certification-program)

**Comment by glimchb** [comment]
@samerhaj thanks for the comment, do you want to commit this inside the page ? (otherwise we can loose it as just a comment here)... WDYT ?

**Comment by samerhaj** [comment]
@glimchb yes that is a good idea. Below is a suggested bullet. I can submit a PR (or Issue) if needed. Just let me know:


> ### Assumptions
> 
> - The infrastructure devices must follow the PCI spec and be ready on the bus(es) at enumeration time, and/or hot plug devices in and out dynamically.
> - Drivers for both X86 and ARM have to be present at the same time in option ROM (OROM).
> - xPUs running on Arm-based servers are required to use AARCH64 native UEFI Drivers (see the UEFI driver requirements in section 7.3.3.1 of Arm BBR specification (https://developer.arm.com/documentation/den0044/latest)

**Comment by glimchb** [comment]
@samerhaj yes, if you can, please submit and PR and we can review and I can merge it

**Pull request merged**
