### PR TITLE
doc: add diagrams for standalone and no-BMC

### PR DESCRIPTION
**Pull request by glimchb**
Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

**Comment by stolsma** [comment]
Is it possible to add a white or other coloured background to the images? The current transparent background doesn't work if you use the github website with the dark template as a lot of people I know do (incl. myself)....

**Comment by glimchb** [comment]
> Reference

@stolsma sure, can you show me how to change it on http://draw.io/ ?

**Comment by stolsma** [comment]
> > Reference
> 
> @stolsma sure, can you show me how to change it on http://draw.io/ ?

Hmmmm.... to be honest I don't have a clue but I will try to find out 🤔

**Comment by glimchb** [comment]
> > > Reference
> > 
> > 
> > @stolsma sure, can you show me how to change it on http://draw.io/ ?
> 
> Hmmmm.... to be honest I don't have a clue but I will try to find out 🤔

:-) same here

**Comment by stolsma** [comment]
@glimchb Found it! Right side on the Diagram tab->background box! 😀

**Comment by glimchb** [comment]
> @glimchb Found it! I think... 😊Right side on the Diagram tab->background box! 😀

great, thanks

**Review by mestery — APPROVED** [review]
Good enough to merge!

**Comment by glimchb** [comment]
@stolsma I will merge this and then we change background as a separate commit, hope this works for you

**Pull request merged**
